"""Email notification service.

For development, this logs the email content instead of
sending actual emails.
"""

import aiosmtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from app.core.config import settings
from app.core.logging import get_logger

logger = get_logger(__name__)


class EmailNotifier:
    """
    Service for sending email notifications.

    In development mode (LOG_ONLY=true), logs instead of sending.
    """

    def __init__(self, log_only: bool = True):
        """
        Initialize email notifier.

        Args:
            log_only: If True, log instead of sending (for development)
        """
        self.log_only = log_only

    async def send(self, to_email: str, subject: str, content: str):
        """
        Send an email notification.

        Args:
            to_email: Recipient email address
            subject: Email subject
            content: Markdown content (will be converted to HTML)

        Raises:
            Exception: If sending fails
        """
        if self.log_only:
            # Development mode: log instead of sending
            logger.info(
                "[Email - LOG MODE] Would send email",
                extra={
                    "to": to_email,
                    "subject": subject,
                    "content_length": len(content),
                    "content_preview": content[:300] + "..." if len(content) > 300 else content,
                },
            )
            return

        # Production mode: send actual email
        try:
            # Create message
            message = MIMEMultipart("alternative")
            message["From"] = settings.FROM_EMAIL
            message["To"] = to_email
            message["Subject"] = subject

            # Add plain text version
            plain_text = self._markdown_to_plain(content)
            part1 = MIMEText(plain_text, "plain")

            # Add HTML version
            html_content = self._markdown_to_html(content)
            part2 = MIMEText(html_content, "html")

            message.attach(part1)
            message.attach(part2)

            # Send email
            await aiosmtplib.send(
                message,
                hostname=settings.SMTP_HOST,
                port=settings.SMTP_PORT,
                username=settings.SMTP_USER,
                password=settings.SMTP_PASSWORD,
                use_tls=True,
                start_tls=False,
            )

            logger.info("Email sent successfully", extra={"to": to_email, "subject": subject})

        except Exception as e:
            logger.error(f"Failed to send email: {e}")
            raise

    def _markdown_to_plain(self, markdown: str) -> str:
        """
        Convert Markdown to plain text.

        Args:
            markdown: Markdown content

        Returns:
            Plain text
        """
        # Simple conversion - remove Markdown syntax
        lines = markdown.split("\n")
        plain_lines = []

        for line in lines:
            # Remove headers
            line = line.lstrip("#")
            # Remove bold
            line = line.replace("**", "").replace("__", "")
            # Remove links
            line = line.replace("[", "").replace("](", " ").replace(")", "")
            # Remove horizontal rules
            if line.strip() == "---":
                line = "-" * 20
            plain_lines.append(line)

        return "\n".join(plain_lines)

    def _markdown_to_html(self, markdown: str) -> str:
        """
        Convert Markdown to HTML.

        Args:
            markdown: Markdown content

        Returns:
            HTML string
        """
        # Simple conversion - for production, use a proper library like markdown
        html = f"""
        <html>
        <body>
            <h2 style="color: #333;">{self._extract_first_header(markdown)}</h2>
            <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #555;">
                {self._markdown_body_to_html(markdown)}
            </div>
            <hr style="margin-top: 20px; border: 0; border-top: 1px solid #eee;">
            <p style="font-size: 12px; color: #999;">
                This digest was generated by X-News-Digest
            </p>
        </body>
        </html>
        """
        return html

    def _extract_first_header(self, markdown: str) -> str:
        """Extract the first header from markdown."""
        for line in markdown.split("\n"):
            if line.strip().startswith("#"):
                return line.lstrip("#").strip()
        return "Digest"

    def _markdown_body_to_html(self, markdown: str) -> str:
        """Convert markdown body to HTML."""
        html = markdown

        # Headers
        html = html.replace("### ", "<h3>").replace("\n", "</h3>\n", 1)
        html = html.replace("## ", "<h2>").replace("\n", "</h2>\n", 1)

        # Bold
        html = html.replace("**", "<strong>").replace("**", "</strong>")

        # Links
        # (simplified - not a full implementation)

        # Line breaks
        html = html.replace("\n\n", "<br/><br/>")

        return html


__all__ = ["EmailNotifier"]
