"""Markdown rendering for digests."""

from datetime import datetime
from app.services.llm.client import DigestResult


def render_markdown_digest(
    topic_name: str,
    digest_result: DigestResult,
    time_window_start: datetime,
    time_window_end: datetime,
) -> str:
    """
    Render a digest as formatted Markdown.

    Args:
        topic_name: Name of the topic
        digest_result: DigestResult from LLM
        time_window_start: Start of time window
        time_window_end: End of time window

    Returns:
        Rendered Markdown string
    """
    # Format time window
    time_str = f"{time_window_start.strftime('%Y-%m-%d %H:%M')} - {time_window_end.strftime('%Y-%m-%d %H:%M')}"

    # Build markdown
    lines = [
        f"# {digest_result.headline}\n",
        f"**Topic:** {topic_name}\n",
        f"**Period:** {time_str}\n",
        f"**Sentiment:** {digest_result.sentiment.capitalize()}\n",
    ]

    # Add themes
    if digest_result.themes:
        lines.append(f"\n**Themes:** {', '.join(digest_result.themes)}\n")

    # Add highlights
    lines.append("\n## Highlights\n")
    for highlight in digest_result.highlights:
        lines.append(f"### {highlight.title} (Score: {highlight.score}/10)\n")
        lines.append(f"{highlight.summary}\n")

        # Add representative URLs
        if highlight.representative_urls:
            lines.append("**Sources:**\n")
            for url in highlight.representative_urls:
                lines.append(f"- [{url}]({url})\n")
        lines.append("\n")

    # Add statistics
    lines.append("## Statistics\n")
    stats = digest_result.stats
    lines.append(f"- **Total posts analyzed:** {stats.total_posts_analyzed}\n")
    lines.append(f"- **Unique authors:** {stats.unique_authors}\n")
    lines.append(f"- **Total engagement:** {stats.total_engagement:,}\n")
    lines.append(f"- **Avg engagement per post:** {stats.avg_engagement_per_post:.1f}\n")

    # Add footer
    lines.append("\n---\n")
    lines.append(f"*Generated by X-News-Digest on {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}*\n")

    return "".join(lines)
